version: "3.7"

services:
    nginx:
        restart: unless-stopped
        ports:
            - 80
            - 443

    app:
        restart: unless-stopped
        environment:
            - NODE_ENV=production

    bd:
        restart: unless-stopped
