version: "3.7"

services:
    # nginx:
    #     ports:
    #         - "8000:80"
    #         - 443
    #     volumes:
    #         - ./nginx_default.conf:/etc/nginx/conf.d/default
    #         - ./nginx_default.conf:/etc/nginx/sites-available/default
    #         - ../src/logs/nginx:/usr/local/nginx/logs
    #         - ../src/logs/nginx:/var/log/nginx

    # front_blog:
    #     volumes:
    #         - ../src/tech_overload_blog:/application
    #     environment:
    #         - NODE_ENV=development
    #     entrypoint: ["/application/dev_entrypoint.sh"]
    #     restart: on-failure

    # front_admin_panel:
    #     volumes:
    #         - ../src/admin_panel:/application
    #     entrypoint: ["/application/dev_entrypoint.sh"]
    #     environment:
    #         - NODE_ENV=development
    #     restart: on-failure

    bluro:
        volumes:
            - ../src/bluro_cms:/application
        entrypoint: ["/application/dev_entrypoint.sh"]
        environment:
            - NODE_ENV=development
        restart: on-failure
