version: "3.7"

services:
    nginx:
        volumes:
            # - ./nginx_default.conf:/etc/nginx/nginx.conf
            - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx_default.conf:/etc/nginx/sites-available/default.conf
            - ../src/logs/nginx:/usr/local/nginx/logs
            - ../src/logs/nginx:/var/log/nginx
        restart: on-failure

    front_blog:
        volumes:
            - ../src/tech_overload_blog:/application
        environment:
            - NODE_ENV=development
        entrypoint: ["/application/dev_entrypoint.sh"]
        restart: on-failure
        stdin_open: true

    # front_admin_panel:
    #     volumes:
    #         - ../src/admin_panel:/application
    #     entrypoint: ["/application/dev_entrypoint.sh"]
    #     environment:
    #         - NODE_ENV=development
    #     restart: on-failure
    # stdin_open: true

    bluro_api:
        volumes:
            - ../src/bluro_cms:/application
        entrypoint: ["/application/dev_entrypoint.sh"]
        environment:
            - NODE_ENV=development
        restart: on-failure
