version: "3.7"

services:
    nginx:
        restart: unless-stopped

    front_blog:
        build:
            context: ../tech_overload_blog/build
            dockerfile: ./dockerfile_front_prod
        restart: unless-stopped

    front_admin_panel:
        build:
            context: ../admin_panel/build
            dockerfile: ./dockerfile_front_prod
        restart: unless-stopped

    bluro_api:
        build:
            context: ../bluro_cms
            dockerfile: ./dockerfile_front_prod
        volumes:
            - ../app_data/api/logs:/application/logs
            - ../app_data/api/static_files:/application/files
        restart: unless-stopped
        environment:
            - NODE_ENV=production

    bd:
        restart: unless-stopped
