version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - front_blog
            # - front_admin_panel
        networks:
            - bluro

    front_blog:
        image: node:latest
        depends_on:
            - db
            - bluro_api
        env_file:
            - front.env
        networks:
            - bluro
        expose:
            - "8000"

    # front_admin_panel:
    #     image: node:latest
    #     depends_on:
    #         - db
    #         - bluro_api
    #     expose:
    #         - "3000"
    #     env_file:
    #         - front.env
    #     networks:
    #         - bluro

    bluro_api:
        image: node:latest
        depends_on:
            - db
        env_file:
            - api.env
        expose:
            - "8000"
        networks:
            - bluro

    db:
        image: "hypriot/rpi-mysql"
        expose:
            - "3306"
        restart: always
        env_file:
            - db.env
        networks:
            - bluro

networks:
    bluro:
        driver: bridge
