version: "3.7"

services:
    nginx:
        volumes:
            - ./proxy_server.conf:/etc/nginx/conf.d/default.conf
            - ./proxy_server.conf:/etc/nginx/sites-available/default.conf
            - ../app_data/proxy_server:/usr/local/nginx/logs
            - ../app_data/proxy_server:/var/log/nginx
        restart: on-failure

    front_blog:
        image: node:latest
        volumes:
            - ../tech_overload_blog:/application
            - ./dev_entrypoint.sh:/dev_entrypoint.sh
        environment:
            - NODE_ENV=development
        env_file:
            - front.env
        entrypoint: ["/dev_entrypoint.sh"]
        restart: on-failure
        stdin_open: true

    front_admin_panel:
        image: node:latest
        volumes:
            - ../admin_panel:/application
            - ./dev_entrypoint.sh:/dev_entrypoint.sh
        entrypoint: ["/dev_entrypoint.sh"]
        environment:
            - NODE_ENV=development
        env_file:
            - front.env
        restart: on-failure
        stdin_open: true

    bluro_api:
        volumes:
            - ../bluro_cms:/application
            - ./dev_entrypoint.sh:/dev_entrypoint.sh
        entrypoint: ["/dev_entrypoint.sh"]
        environment:
            - NODE_ENV=development
        restart: on-failure
