const DataTypesId = {
	TINY_INT: "TINY_INT",
	SMALL_INT: "SMALL_INT",
	MEDIUM_INT: "MEDIUM_INT",
	INT: "INT",
	BIG_INT: "BIG_INT",

	BIT: "BIT",

	FLOAT: "FLOAT",
	DOUBLE: "DOUBLE",
	DECIMAL: "DECIMAL",

	VARCHAR: "VARCHAR",

	VARBINARY: "VARBINARY",
	JSON: "JSON",

	TIME: "TIME",
	DATE: "DATE",
	DATE_TIME: "DATE_TIME",
};

module.exports = DataTypesId;
